### ISSUE TITLE
how to preprocess the GTSDB dataset

### ISSUE THREAD

**Issue by ntut108318099** [hellojialee/Traffic_Sign_Recognition_Efficient_CNNs#12]
hello,I am the student in graduate school now. I am very interested in this paper.
I want to redo the detection part,but I don't know how to preprocess the GTSDB dataset.
Can you tell me how to do this or what paper can refer? 
Thank you very much.

email: jasonlee10805@gmail.com
name: jason

**Comment by jialee93** [comment]
Hi friend, I cannot remember the details anymore. After reading and preparing the GTSDB data, do make sufficient augmentations during training, such as random flip, resizing, color tint, and poisson blending although we didn't mention these tricks clearly. I don't remember whether the coordinate shifting is beneficial too and you could also have a try.

 Some other new augmentation techniques such as mix-up may be useful. You can refer to some papers studying the generation of reliable training samples and model generalization but I haven't follow. 

GTSDB dataset is small but difficult, and more abundant new benchmarks are worthy of trying. Hope you make progress :)

**Comment by ntut108318099** [comment]
Thank you for your reply.I will refer reliable samples to prepare to train.
Sorry to bother you.Please let me ask one more question.You say there are more abundant new traffic scene benchmarks. Can you tell me what benchmarks can use and in this field, what problem

**Comment by hellojialee** [comment]
I haven't follow this area for a long time. Here is a good repo you may be interested: https://github.com/daohu527/Dig-into-Apollo
Just search resources everywhere and best wishes to you.

**Comment by ntut108318099** [comment]
Thank you a lot!!
I will search and learn more about this area.The repo you offer really help me a lot.
Best wishes to you.

**Comment by hellojialee** [comment]
Best wishes to you, too! Hope you make progress :)
